<?php

namespace Database\Seeders;

use App\Models\SiteTemplate;
use App\Models\SiteTemplateField;
use Illuminate\Database\Seeder;

class Template1SiteTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $siteTemplate = SiteTemplate::updateOrCreate(
            ['slug' => 'template_1'],
            [
                'name' => 'Template 1',
                'slug' => 'template_1',
                'blade_view' => 'template.template_1',
                'sports' => null,
                'preview_image' => null,
                'description' => 'A tab-based athlete profile template with About Me, Schedule, Highlights, Accolades, coaching staff, footer contact details, and built-in SEO fields.',
                'is_active' => true,
                'settings' => null,
            ]
        );

        $fields = [
            [
                'name' => 'aboutme_headline',
                'label' => 'About Me Headline',
                'type' => 'text',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 10,
                'options' => null,
            ],
            [
                'name' => 'player_tagline',
                'label' => 'Player Tagline',
                'type' => 'text',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 20,
                'options' => null,
            ],
            [
                'name' => 'player_bio',
                'label' => 'Player Bio',
                'type' => 'richtext',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 30,
                'options' => null,
            ],
            [
                'name' => 'yt_embed',
                'label' => 'About Video URL(s)',
                'type' => 'textarea',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 40,
                'options' => null,
            ],
            [
                'name' => 'highlights_thumbnail',
                'label' => 'Highlights Thumbnail',
                'type' => 'image',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 50,
                'options' => null,
            ],
            [
                'name' => 'schedules_headline',
                'label' => 'Schedules Headline',
                'type' => 'text',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 60,
                'options' => null,
            ],
            [
                'name' => 'schedules_tagline',
                'label' => 'Schedules Tagline',
                'type' => 'text',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 70,
                'options' => null,
            ],
            [
                'name' => 'highlights_headline',
                'label' => 'Highlights Headline',
                'type' => 'text',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 80,
                'options' => null,
            ],
            [
                'name' => 'highlights_tagline',
                'label' => 'Highlights Tagline',
                'type' => 'text',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 90,
                'options' => null,
            ],
            [
                'name' => 'yt_playlist_embed',
                'label' => 'Highlight Video URL(s)',
                'type' => 'textarea',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 100,
                'options' => null,
            ],
            [
                'name' => 'acad_accolades_headline',
                'label' => 'Academic Accolades Headline',
                'type' => 'text',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 110,
                'options' => null,
            ],
            [
                'name' => 'acad_accolades_tagline',
                'label' => 'Academic Accolades Tagline',
                'type' => 'text',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 120,
                'options' => null,
            ],
            [
                'name' => 'academic_accolades',
                'label' => 'Academic Accolades',
                'type' => 'textarea',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 130,
                'options' => null,
            ],
            [
                'name' => 'sport_accolades_headline',
                'label' => 'Sport Accolades Headline',
                'type' => 'text',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 140,
                'options' => null,
            ],
            [
                'name' => 'sport_accolades_tagline',
                'label' => 'Sport Accolades Tagline',
                'type' => 'text',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 150,
                'options' => null,
            ],
            [
                'name' => 'sports_accolades',
                'label' => 'Sports Accolades',
                'type' => 'textarea',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 160,
                'options' => null,
            ],
            [
                'name' => 'contact_form_embed',
                'label' => 'Contact Form Embed',
                'type' => 'embed',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 170,
                'options' => null,
            ],
            [
                'name' => 'logos',
                'label' => 'Footer Logo',
                'type' => 'image',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 180,
                'options' => null,
            ],
            [
                'name' => 'seo_title',
                'label' => 'SEO Title',
                'type' => 'text',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 190,
                'options' => null,
            ],
            [
                'name' => 'seo_description',
                'label' => 'SEO Description',
                'type' => 'textarea',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 200,
                'options' => null,
            ],
            [
                'name' => 'seo_keywords',
                'label' => 'SEO Keywords',
                'type' => 'textarea',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 210,
                'options' => null,
            ],
            [
                'name' => 'seo_robots',
                'label' => 'SEO Robots',
                'type' => 'text',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 220,
                'options' => null,
            ],
            [
                'name' => 'seo_canonical_url',
                'label' => 'SEO Canonical URL',
                'type' => 'url',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 230,
                'options' => null,
            ],
            [
                'name' => 'og_title',
                'label' => 'Open Graph Title',
                'type' => 'text',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 240,
                'options' => null,
            ],
            [
                'name' => 'og_description',
                'label' => 'Open Graph Description',
                'type' => 'textarea',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 250,
                'options' => null,
            ],
            [
                'name' => 'og_image',
                'label' => 'Open Graph Image',
                'type' => 'image',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 260,
                'options' => null,
            ],
            [
                'name' => 'twitter_title',
                'label' => 'Twitter Title',
                'type' => 'text',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 270,
                'options' => null,
            ],
            [
                'name' => 'twitter_description',
                'label' => 'Twitter Description',
                'type' => 'textarea',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 280,
                'options' => null,
            ],
            [
                'name' => 'twitter_image',
                'label' => 'Twitter Image',
                'type' => 'image',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 290,
                'options' => null,
            ],
            [
                'name' => 'favicon',
                'label' => 'Favicon',
                'type' => 'image',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 300,
                'options' => null,
            ],
            [
                'name' => 'schema_override_name',
                'label' => 'Schema Override Name',
                'type' => 'text',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 310,
                'options' => null,
            ],
            [
                'name' => 'schema_override_description',
                'label' => 'Schema Override Description',
                'type' => 'textarea',
                'guide_image' => null,
                'is_required' => false,
                'sort_order' => 320,
                'options' => null,
            ],
        ];

        foreach ($fields as $field) {
            SiteTemplateField::updateOrCreate(
                [
                    'site_template_id' => $siteTemplate->id,
                    'name' => $field['name'],
                ],
                $field
            );
        }
    }
}