@once
<div class="plyr-amplify-modal" data-plyrcard-jumpstart-modal data-start-url="{{ route('billing.jumpstart.start') }}" data-status-url="{{ route('billing.jumpstart.status') }}" hidden>
    <div class="plyr-amplify-backdrop" data-plyrcard-jumpstart-close></div>
    <div class="plyr-amplify-panel" role="dialog" aria-modal="true" aria-label="Jumpstart secure checkout">
        <button type="button" class="plyr-amplify-close" data-plyrcard-jumpstart-close aria-label="Close">&times;</button>
        <header class="plyr-amplify-head"><span class="plyr-amplify-kicker">JUMPSTART</span><h2>Get Jumpstart</h2><p>Complete the $149 one-time purchase. No subscription is required.</p></header>
        <div class="plyr-amplify-body">
            <div class="plyr-amplify-state" data-plyrcard-jumpstart-loading><div class="plyr-amplify-state-inner"><strong>Preparing secure checkout…</strong></div></div>
            <div class="plyr-amplify-state" data-plyrcard-jumpstart-success hidden><div class="plyr-amplify-state-inner"><strong>Jumpstart confirmed</strong><span>Your one-time recruiting push is active.</span></div></div>
            <div class="plyr-amplify-state" data-plyrcard-jumpstart-error hidden><div class="plyr-amplify-state-inner plyr-amplify-error"><strong>Checkout could not be prepared</strong><span data-plyrcard-jumpstart-error-copy>Please try again.</span><button type="button" class="plyr-amplify-retry" data-plyrcard-jumpstart-retry>Try Again</button></div></div>
            <iframe class="plyr-amplify-frame" data-plyrcard-jumpstart-frame src="about:blank" scrolling="no" id="CXioZTT8ncW1xtwZuLVt" title="Jumpstart secure checkout" data-cookie-consent="true" data-cookie-consent-provider="auto" hidden></iframe>
        </div>
        <footer class="plyr-amplify-foot"><span data-plyrcard-jumpstart-status>Payment confirmation is checked automatically.</span><strong>Secure checkout</strong></footer>
    </div>
</div>
<script src="https://systems.plyrcard.com/js/form_embed.js" defer></script>
<script>
(()=>{if(window.__plyrcardJumpstartCheckout)return;window.__plyrcardJumpstartCheckout=true;const m=document.querySelector('[data-plyrcard-jumpstart-modal]');if(!m)return;const f=m.querySelector('[data-plyrcard-jumpstart-frame]'),loading=m.querySelector('[data-plyrcard-jumpstart-loading]'),success=m.querySelector('[data-plyrcard-jumpstart-success]'),error=m.querySelector('[data-plyrcard-jumpstart-error]'),errorCopy=m.querySelector('[data-plyrcard-jumpstart-error-copy]'),status=m.querySelector('[data-plyrcard-jumpstart-status]');let timer=null,started=0,busy=false;const csrf=()=>document.querySelector('meta[name="csrf-token"]')?.content||'';const show=t=>{[loading,success,error,f].forEach(x=>{if(x)x.hidden=x!==t})};const req=async(url,opt={})=>{const r=await fetch(url,{credentials:'same-origin',headers:{Accept:'application/json','X-Requested-With':'XMLHttpRequest',...(opt.method&&opt.method!=='GET'?{'X-CSRF-TOKEN':csrf(),'Content-Type':'application/json'}:{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.message||'Unable to continue.');return d};const stop=()=>{if(timer)clearTimeout(timer);timer=null};const close=()=>{stop();m.hidden=true;document.documentElement.style.overflow=''};async function poll(){if(m.hidden)return;if(Date.now()-started>12*60*1000){status.textContent='Checkout is still open. Complete payment to activate Jumpstart.';return}try{const d=await req(m.dataset.statusUrl);if(d.completed){stop();show(success);status.textContent='Payment confirmed. Updating your PLYRCARD…';window.dispatchEvent(new CustomEvent('plyrcard:jumpstart-upgraded',{detail:d}));setTimeout(()=>{if(!document.querySelector('[data-lr-drawer]'))window.location.reload()},900);return}status.textContent=d.message||'Waiting for payment confirmation…'}catch(_){status.textContent='Still checking payment confirmation…'}timer=setTimeout(poll,2500)}async function start(){if(busy)return;busy=true;stop();m.hidden=false;document.documentElement.style.overflow='hidden';show(loading);status.textContent='Preparing secure checkout…';try{const d=await req(m.dataset.startUrl,{method:'POST',body:'{}'});if(d.completed){show(success);status.textContent=d.message||'Jumpstart is active.';return}if(!d.checkout_url)throw new Error(d.message||'Secure checkout is unavailable.');f.src=d.checkout_url;show(f);started=Date.now();status.textContent=d.message||'Complete checkout to continue.';timer=setTimeout(poll,1800)}catch(e){show(error);errorCopy.textContent=e.message||'Please try again.';status.textContent='Checkout was not started.'}finally{busy=false}}document.addEventListener('click',e=>{if(e.target.closest('[data-plyrcard-jumpstart-open]')){e.preventDefault();start();return}if(e.target.closest('[data-plyrcard-jumpstart-close]')){close();return}if(e.target.closest('[data-plyrcard-jumpstart-retry]'))start()});})();
</script>
@endonce
