<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Services\GoHighLevelService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class RecruitingProfileViewTrackingController extends Controller
{
    /**
     * Website beacon endpoint for player-profile views.
     *
     * Expected query/body values are generated by GoHighLevelService::appendRecruitingTrackingQueryParameters()
     * or InteractsWithCoachDatabase::appendRecruitingTrackingQuery():
     * rc_athlete_id, rc_contact_id, rc_platform, rc_source, rc_school, rc_business_id,
     * utm_source, utm_medium, utm_campaign, rc_fingerprint.
     */
    public function __invoke(Request $request, GoHighLevelService $goHighLevelService): Response
    {
        $athleteId = $request->input('rc_athlete_id', $request->query('rc_athlete_id'));
        $user = filled($athleteId) ? User::query()->find((int) $athleteId) : $request->user();

        $result = $goHighLevelService->trackRecruitingProfileViewFromRequest($user, $request, [
            'source' => $request->input('rc_source', $request->query('rc_source', 'player_website')),
            'platform' => $request->input('rc_platform', $request->query('rc_platform', $request->query('utm_medium', 'website'))),
            'contact_id' => $request->input('rc_contact_id', $request->query('rc_contact_id', $request->query('rc_ghl_contact_id'))),
            'destination_url' => $request->input('destination_url', $request->fullUrl()),
        ]);

        return response('', ($result['success'] ?? false) ? 204 : 202)
            ->header('Cache-Control', 'no-store, no-cache, must-revalidate, max-age=0')
            ->header('Pragma', 'no-cache');
    }
}