<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PLYRCARD activity</title></head>
<body style="margin:0;padding:0;background:#0C0E11;color:#F2F0ED;font-family:Inter,Arial,sans-serif;">
@php
$isProfile = $activityType === 'profile_view';
$label = $isProfile ? 'Profile view' : strtoupper($platform).' click';
$title = $isProfile ? 'Someone viewed your PLYRCARD.' : 'Someone clicked your '.ucfirst($platform).' link.';
$url = filled($website->domain) ? 'https://'.preg_replace('/^https?:\/\//','',$website->domain) : url('/'.ltrim((string)$website->slug,'/'));
@endphp
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" bgcolor="#0C0E11"><tr><td align="center" style="padding:32px 12px;"><table role="presentation" width="600" style="width:600px;max-width:600px;"><tr><td style="padding:0 34px 22px;font-family:Archivo,Arial,sans-serif;font-size:19px;font-weight:800;">PLYR<span style="color:#FF5A3C;">CARD</span></td></tr><tr><td bgcolor="#131619" style="border-radius:14px;border:1px solid #1E242A;"><table role="presentation" width="100%"><tr><td style="padding:38px 34px 0;"><div style="font-family:'Courier New',monospace;font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#FF5A3C;">{{ $label }}</div><h1 style="margin:12px 0 0;font-family:Archivo,Arial,sans-serif;font-size:32px;line-height:1.1;">{{ $title }}</h1><p style="margin:14px 0 0;font-size:15px;line-height:1.6;color:#868E99;">{{ $isProfile ? 'Your profile got another visit.' : 'A visitor moved from your PLYRCARD to your '.$platform.' destination.' }}</p></td></tr><tr><td style="padding:26px 34px 0;"><table role="presentation" width="100%" bgcolor="#1A1E23" style="border:1px solid #262C33;border-radius:12px;"><tr><td style="padding:22px;"><div style="font-family:'Courier New',monospace;font-size:10px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#868E99;">Activity</div><div style="margin-top:10px;font-size:15px;color:#F2F0ED;">{{ $viewerEmail ? 'Visitor: '.$viewerEmail : 'Visitor: anonymous / direct' }}</div><div style="margin-top:8px;font-size:13px;color:#868E99;">{{ now()->format('M j, Y g:i A T') }}</div></td></tr></table></td></tr><tr><td style="padding:26px 34px 0;"><a href="{{ $url }}" style="display:inline-block;padding:15px 34px;background:#FF5A3C;border-radius:10px;color:#0C0E11;text-decoration:none;font-family:Archivo,Arial,sans-serif;font-weight:700;">View my PLYRCARD</a></td></tr><tr><td style="padding:28px 34px 34px;font-size:14px;line-height:1.6;color:#868E99;">Keep your film, stats, schedule, and contact details current so every visit lands on your strongest profile.<div style="margin-top:16px;font-family:Archivo,Arial,sans-serif;font-weight:600;color:#F2F0ED;">This is your journey. It has to come from you.<br><span style="color:#FF5A3C;">Authenticity is Key.</span></div></td></tr></table></td></tr><tr><td align="center" style="padding:24px 34px 0;font-size:11.5px;line-height:1.7;color:#5E6670;">PLYRCARD profile activity notification<br>&copy; 2026 PLYRCARD.</td></tr></table></td></tr></table></body></html>
